import React, { useState } from "react";
import type { NextPage } from "next";
import Image from "next/image";
import Head from "next/head";
// import styles from "../styles/otherstyle/market.scss";
import styles from "styles/otherstyle/home.module.scss";

const Home: NextPage = () => {
  const [src, setSrc] = useState("");
  return (
    <div className={styles.container}>
      <Head>
        <title>Epic Global</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/epic logo.png" />
      </Head>
      <section className="section2">
        <div className="containerr">
          <div className="row">
            <div className="col-md-6">
              <div className={styles.section2content}>
                <h2>WHO WE ARE</h2>
                <p>
                  Epic Global is a specialized tech venture that offers complete
                  website design, development and digital marketing solutions to
                  the business. The company uses best in class technology to
                  help their client’s business get recognized across the world
                  using specialized digital channels like SEO, CRM, Paid
                  campaigns, ecommerce integration and a lot more.
                </p>
                <p>
                  Our prime purpose is to create web applications and processes
                  that can further enhance the engagement and traffic of your
                  website despite the tough market competition. Out digital
                  marketing initiatives are backed by the team of professionals
                  who can assist in bringing organic and paid traffic to your
                  web application and make your business grow at faster rate. We
                  have strengthened our hold not only in India, but boosts off
                  satisfied clientele spread across the globe.
                </p>
              </div>
            </div>
            <div className="col-md-6">
              <div className={styles.Imgcontainerr2}>
                <Image
                  src="/epic global/Group 62 (1).png"
                  height={1000}
                  width={1100}
                />
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className={` ${styles.marketing} section2`}>
        <div className="containerr3">
          <div className="row">
            <div className="col-md-12">
              <div className={styles.section2DigitalMarketing}>
                <h2>DIGITAL MARKETING SERVICES</h2>
                <p>
                  We boost your organization througour quality services so that
                  you are able to reach your business goals and thus get the
                  success you had always wanted.
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className={styles.MarkitingSection}>
        <div className="containerr">
          <div className="row">
            <div className="col-md-12">
              <div className={styles.MarkitingImage}>
                <ul>
                  <li>
                    <Image
                      src="/epic global/sale_229497_article_image-100886210-large.jpg"
                      height={500}
                      width={500}
                    />
                  </li>

                  <li>
                    <Image
                      src="/epic global/original-1980fec3aadf6b9f52b8c89806ee731e.jpg"
                      height={500}
                      width={500}
                    />
                  </li>
                  <li>
                    <Image
                      src="/epic global/sale_229497_article_image-100886210-large.jpg"
                      height={500}
                      width={500}
                    />
                  </li>

                  <li>
                    <Image
                      src="/epic global/choose-3.jpg"
                      height={500}
                      width={500}
                    />
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className={styles.socialimage}>
        <div className="containerr">
          <div className="row">
            <div className="col-md-8">
              <div className={styles.image1}>
                <Image
                  src="/epic global/Group 17.png"
                  height={500}
                  width={1600}
                />
              </div>
            </div>
            <div className="col-md-4"></div>
          </div>
        </div>
      </section>
      <section className={styles.socialcontent}>
        <div className="containerr">
          <div className="row">
            <div className="col-md-7">
              <p>
                We put together successful digital marketing campaigns for
                organizations of all sizes. We can do the same for you. Request
                a free quote now and you would get to know why Epic web techno
                is the best SEO organization among all.
              </p>
              <span>
                <input
                  type="text"
                  className={styles.searchbar}
                  placeholder="Enter your website"
                />
                <button className={styles.searchbarButton}>Submit</button>
              </span>
            </div>

            <div className="col-md-5">
              <div className={styles.socilrotate}>
                <div className={styles.section3Expand}>
                  <h1>
                    ARE YOU READY TO <span>GROW</span>?
                  </h1>
                </div>
                <div className={styles.section3ExpandSocial}>
                  <h1>
                    IF, YES, THEN GET YOUR FREE QUOTE <span>TODAY</span>.
                  </h1>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section>
        <div className={styles.mainImageDiv}>
          <div className={styles.mainImageDivHeadingDiv}>
            <h1>
              Kick start your strategic campaign today! or mail
              hello@epicglobal.com
            </h1>
          </div>
        </div>
      </section>
      <section className={styles.StartupBusinesscontent}>
        <div className="containerr">
          <div className="row">
            <div className="col-md-6">
              <h1>Who We Work With</h1>
              <p>
                In a competitive world driven by technology, we strive to
                provide much more than just plain satisfaction. Our motto is –
                To assist and associate as partners with our clients. This is
                the reason we believe that utilization of the web should not be
                a struggle; in fact, it should be a worry-free journey.
              </p>
              <div className={styles.contant2}>
                <p>
                  <span>
                    And, thus at Epic Global we are committed to add value to
                    your business through intelligent use of the digital
                    channels.
                  </span>
                </p>
              </div>

              <div className={styles.contant3}>
                <p>
                  <span>
                    By serving huge numbers of diverse clients worldwide, we
                    have managed to establish our unique recognition among our
                    valued customers within a short span of 3 years.
                  </span>
                </p>
              </div>
            </div>

            <div className="col-md-6">
              <div className={styles.EmployeeImage}>
                <div className={styles.EmployeeImageSection2}>
                  <ul>
                    <li>
                      <div className={styles.image1s}>
                        <Image
                          src="/epic global/employee.png"
                          height={150}
                          width={150}
                        />
                      </div>
                      <h2>Startup Business</h2>
                    </li>
                    <li>
                      <div className={styles.image1se}>
                        <Image
                          src="/epic global/minimize.png"
                          height={150}
                          width={150}
                        />
                      </div>
                      <h2>
                        Small and Medium<br></br>Business
                      </h2>
                    </li>
                  </ul>
                </div>
                <div className={styles.EmployeeImageSection34}>
                  <ul>
                    <li>
                      <div className={styles.image1s}>
                        <Image
                          src="/epic global/office-building.png"
                          height={150}
                          width={150}
                        />
                      </div>
                      <h2>Agencies</h2>
                    </li>
                    <li>
                      <div className={styles.image1s}>
                        <Image
                          src="/epic global/briefcase.png"
                          height={150}
                          width={150}
                        />
                      </div>
                      <h2>Enterprise</h2>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className="section4">
        <div className="containerr4">
          <div className="row">
            <div className="col-md-12">
              <div className={styles.WorkingProcessContant}>
                <h1>The Working Process</h1>
                <p>
                  Epic will help in continuous improvement of any project. Our
                  working process policy is based on research, strategy,
                  development and optimization of your project.
                </p>
                <ul>
                  <li>
                    <Image
                      src="/epic global/Group 50.png"
                      height={600}
                      width={1000}
                    />
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className={styles.hadingBussinessSection}>
        <div className="containerr">
          <div className="row">
            <div className="col-md-12">
              <h1>The better information about the virtual world.</h1>
            </div>
          </div>
        </div>
      </section>

      <section className="section2">
        <div className="containerr">
          <div className="row">
            <div className="col-md-6">
              <div className={styles.BeauticianSection}>
                <h2>Book Beautician</h2>
                <p>
                  Book Beautician is a nail art studio with a team of talented,
                  passionate and creative people with years of experience
                  dedicated to doing great nails.
                </p>
                <button>Know more</button>
              </div>
            </div>
            <div className="col-md-6">
              <div className={styles.BeauticianSectionImages}>
                <Image src="/epic global/1.png" height={700} width={1000} />
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className="section2">
        <div className="containerr">
          <div className="row">
            <div className="col-md-12">
              <div className={styles.DifferentSectionHeading}>
                <h1>We Different From Others</h1>
              </div>
            </div>
          </div>
        </div>
      </section>

      <section className="section4">
        <div className="containerr">
          <div className="row">
            <div className="col-md-8">
              <div className="row">
                <div className="col-md-6">
                  <div className={styles.ggufi}>
                    <h1>Industry Experts</h1>
                    <p>
                      Lorem ipsum dolor sit amet, consectetur adipiscing elit,
                      sed do eiusmod tempor incididunt ut labore et dolore
                    </p>
                  </div>
                </div>
                <div className="col-md-6">
                  <div className={styles.industry}>
                    <div className={styles.industryimage}>
                      <Image src={src} height={400} width={400} />
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className="col-md-4">
              <div className={styles.ButtonIndustryExperts}>
                <ul>
                  <li className={styles.active}>
                    <button
                      onMouseOver={() =>
                        setSrc("/epic global/news-8-550x500.jpg")
                      }
                    >
                      {" "}
                      Industry Experts
                    </button>
                  </li>
                  <li>
                    <button
                      onMouseOver={() => setSrc("/epic global/choose-2.jpg")}
                    >
                      Dedicated Team
                    </button>
                  </li>
                  <li>
                    <button
                      onMouseOver={() => setSrc("/epic global/choose-3.jpg")}
                    >
                      Outcome Focused
                    </button>
                  </li>
                  <li>
                    <button
                      onMouseOver={() => setSrc("/epic global/choose-4.jpg")}
                    >
                      High Quality Service
                    </button>
                  </li>
                  <li>
                    <button
                      onMouseOver={() => setSrc("/epic global/choose-5.jpg")}
                    >
                      Cyber Security Expert
                    </button>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
};

export default Home;
